baseURL: https://blog.aristocat.in/
languageCode: en-us
title: Thariq's workplace
copyright: "© [thariq shah](https://github.com/thariqshah)"
theme: ["PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Thariq's workplace
  description: "Tech blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon.png"
    favicon16x16: "images/favicon.png"
    favicon32x32: "images/favicon.png"
    apple_touch_icon: "images/favicon.png"
    safari_pinned_tab: "images/favicon.png"

  label:
    text: "Thariq's Workplace"
    iconHeight: 35
    icon: /images/favicon.png

  profileMode:
    enabled: false
    title: Thariq Shah
    subtitle: "Java | Spring | K8s | Microservices | Go"
    imageUrl: "images/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts

  homeInfoParams:
    Title: "Hello world, I'm Thariq \U0001F44B"
    Content: >
      As an experienced software engineer with a passion for solving problems and breaking stuffs.
      My blog explores real-world tech challenges I faced and hobby projects I worked on.

  socialIcons:
    - name: email
      url: mailto:thariqshah@gmail.com
    - name: github
      url: "https://github.com/thariqshah"
    - name: linkedin
      url: "https://www.linkedin.com/in/thariq-shah"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/thariqshah/blog/content"
    Text: "Suggest Changes"
    appendFilePath: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
      about: about
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 1
        - identifier: series
          name: Series
          url: /series/
          weight: 2
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 3
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 4
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 5
        - identifies: about
          name: About me
          url: /about/
          weight: 10

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai